name: Build And Test

on:
  workflow_dispatch:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  BuildTest:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Windows_MingGW
            flavor: Release
            runner: windows-latest
            generator: MinGW Makefiles
            qtver: 5.15.2
            qtdir: mingw81_64
            qtstr: windows desktop win64_mingw81
            build: build

          - name: Windows_Release
            flavor: Release
            runner: windows-latest
            generator: Visual Studio 16 2019
            qtver: 5.15.2
            qtdir: msvc2019_64
            qtstr: windows desktop win64_msvc2019_64
            win64msvc: 1
            build: build_win64msvc
            publish: true

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2

      #
      # Setup and Configuration
      #
      - name: Linux - Setup
        if: ${{ startsWith(matrix.runner, 'ubuntu') }}
        run: |
          sudo add-apt-repository -y ppa:neovim-ppa/stable
          sudo apt-get install -y neovim ninja-build libqt5svg5 libqt5svg5-dev qt5-default
          sudo apt-get update -y

      - name: MacOS - Setup
        if: ${{ startsWith(matrix.runner, 'macos') }}
        run: |
          brew install neovim
          brew ls --formula | grep -wq ninja || brew install ninja
          brew ls --formula | grep -wq qt5 || brew install qt5
          brew ls --formula | grep -wq msgpack || brew install msgpack
          brew link qt5 --force

      - name: Windows - Setup
        if: ${{ startsWith(matrix.runner, 'windows') }}
        env:
          QT_DIR: ${{ github.workspace }}\${{ matrix.qtver }}\${{ matrix.qtdir }}
        run: |
          New-Item -Path .\${{ matrix.build }} -Name "${{ matrix.build }}" -ItemType "directory"
          Invoke-WebRequest https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip -OutFile nvim-win64.zip
          Expand-Archive -Path nvim-win64.zip -DestinationPath .\${{ matrix.build }}\
          Add-Content -Path $env:GITHUB_PATH -Value ${{ github.workspace }}\${{ matrix.build }}\Neovim\bin\
          Add-Content -Path $env:GITHUB_ENV -Value "CMAKE_PREFIX_PATH=$env:QT_DIR;$env:QT_DIR\lib\cmake"
          Add-Content -Path $env:GITHUB_PATH -Value "${{ env.qt_dir }}"
          Add-Content -Path $env:GITHUB_PATH -Value "${{ env.qt_dir }}\bin"

      - name: Qt Cache Restore
        if: ${{ matrix.qtver }}
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ matrix.qtver }}\${{ matrix.qtdir }}
          key: qt-${{ runner.os }}-${{ matrix.qtver }}-${{ matrix.qtdir }}

      - name: Qt Cache Install
        if: ${{ matrix.qtver && steps.cache-qt.outputs.cache-hit != 'true' }}
        run: |
          pip install aqtinstall
          python -m aqt install ${{ matrix.qtver }} ${{ matrix.qtstr }}

      #
      # Build and Test
      #
      - name: Neovim Version
        run: nvim --version

      - name: Configure No MSVC
        if: ${{ !matrix.win64msvc }}
        env:
          CMAKE_BUILD_TYPE: ${{ matrix.flavor }}
          CMAKE_GENERATOR: ${{ matrix.generator }}
        run: >
          cmake -B ./build
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
          -DCMAKE_C_COMPILER=${{ matrix.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
      
      - name: Configure Windows with MSVC
        if: ${{ matrix.win64msvc }}
        env:
          CMAKE_BUILD_TYPE: ${{ matrix.flavor }}
          CMAKE_GENERATOR: ${{ matrix.generator }}
        run: >
          cmake -B ./${{ matrix.build }} -A x64
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install_win64msvc

      - name: Build No MSVC
        if: ${{ !matrix.win64msvc }} 
        run: cmake --build ${{ github.workspace }}/build
      
      - name: Build Windows with MSVC
        if: ${{ matrix.win64msvc }}
        run: cmake --build ${{ github.workspace }}/${{ matrix.build }} --config ${{ matrix.flavor }}

      - name: Test
        if: ${{ !startsWith(matrix.runner, 'windows') }}
        uses: GabrielBB/xvfb-action@v1 # Required by Linux, no X11 $DISPLAY
        with:
          working-directory: ${{ github.workspace }}/build
          run: ctest --output-on-failure -C ${{ matrix.flavor }}

      #
      # Deploy Release Binaries
      #
      - name: Linux - Publish Release Build
        if: ${{ matrix.publish && startsWith(matrix.runner, 'ubuntu') }}
        env:
          ARCH: x86_64
        run: |
          cmake --build ./build --target install
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage ./install/share/applications/nvim-qt.desktop -appimage

      - name: MacOS - Publish Release Build
        if: ${{ matrix.publish && startsWith(matrix.runner, 'macos') }}
        run: |
          macdeployqt ./build/bin/nvim-qt.app -dmg
          mv ./build/bin/nvim-qt.dmg neovim-qt.dmg

      - name: Windows - Publish Release Build
        if: ${{ matrix.publish && startsWith(matrix.runner, 'windows') }}
        run: |
          cmake --build ./${{ matrix.build }} --target install
          Push-Location ${{ github.workspace }}/${{ matrix.build }}
          cpack --verbose -G WIX
          Pop-Location
          Compress-Archive -Path ./install_win64msvc -DestinationPath neovim-qt.zip
          Move-Item -Path ./${{ matrix.build }}/neovim-qt-installer.msi -Destination neovim-qt-installer.msi

      - name: Upload Artifacts
        if: ${{ matrix.publish }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          if-no-files-found: ignore
          path: |
            Neovim-Qt-*-x86_64.AppImage
            neovim-qt.dmg
            neovim-qt-installer.msi
            neovim-qt.zip
